name: Build JUCE VST3

on:
  workflow_dispatch:

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
  
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.2'
  
      - name: Build Plugin (Release x64)
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64
          cmake --build build --config Release
  
      - name: Upload Windows VST3
        uses: actions/upload-artifact@v4
        with:
          name: vst3-windows
          path: build/**/*.vst3


  build-macos:
    name: Build macOS (Universal)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.2'

      - name: Build Universal Plugin
        run: |
          # Tell CMake/Xcode to build both x86_64 and arm64
          cmake -S . -B build -G "Xcode" -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build build --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vst3-macos-universal
          path: build/**/*.vst3
